#!/usr/bin/env groovy
pipeline {
    agent {
        label 'docker-slave'
    }
    stages {
        stage('Compile') {
            steps {
                script {
                    dir("Day5/multi-module-project") {
                        sh "mvn clean compile"
                    }
                }
            }
        }
        stage('Unit Test') {
            steps {
                script {
                    dir("Day5/multi-module-project") {
                        sh "mvn test -P test"
                    }
                }
            }
        }
        stage('package') {
            steps {
                script {
                    dir("Day5/multi-module-project") {
                        sh "mvn package -P package"
                    }
                }
            }
        }
        stage('Install') {
            steps {
                script {
                    dir("Day5/multi-module-project") {
                        sh "mvn install"
                    }
                }
            }
        }
    }
}
